### ISSUE TITLE
Issue with C#

### ISSUE THREAD

**Issue by bobbyislam** [saucelabs/docs#211]
This tutorial does not work. 

A fatal exception occurred while exploring tests.  Possible causes include invalid test runner parameters.
Gallio.Model.ModelException: An exception occurred while invoking a test driver. ---> System.Runtime.Serialization.SerializationException: Type 'Microsoft.Cci.Pdb.PdbDebugException' in Assembly 'Gallio, Version=3.4.0.0, Culture=neutral, PublicKeyToken=eb9cfa67ee6ab36e' is not marked as serializable.
HResult: -2146233076

Server stack trace: 
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
   at System.Runtime.Remoting.Channels.BinaryServerFormatterSink.SerializeResponse(IServerResponseChannelSinkStack sinkStack, IMessage msg, ITransportHeaders& headers, Stream& stream)
   at System.Runtime.Remoting.Channels.BinaryServerFormatterSink.ProcessMessage(IServerChannelSinkStack sinkStack, IMessage requestMsg, ITransportHeaders requestHeaders, Stream requestStream, IMessage& responseMsg, ITransportHeaders& responseHeaders, Stream& responseStream)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Gallio.Model.Isolation.HostedTestIsolationContext.RunIsolatedTaskDelegate.EndInvoke(IAsyncResult result)
   at Gallio.Model.Isolation.HostedTestIsolationContext.RunIsolatedTaskInHost[TIsolatedTask](HostSetup hostSetup, StatusReporter statusReporter, Object[] args) in c:\Server\Projects\MbUnit v3\Work\src\Gallio\Gallio\Model\Isolation\HostedTestIsolationContext.cs:line 127
   at Gallio.Model.Isolation.HostedTestIsolationContext.RunIsolatedTaskImpl[TIsolatedTask](HostSetup hostSetup, StatusReporter statusReporter, Object[] args) in c:\Server\Projects\MbUnit v3\Work\src\Gallio\Gallio\Model\Isolation\HostedTestIsolationContext.cs:line 83
   at Gallio.Model.DotNetTestDriver.ExploreOrRunAssembly(ITestIsolationContext testIsolationContext, TestPackage testPackage, TestExplorationOptions testExplorationOptions, TestExecutionOptions testExecutionOptions, RemoteMessageSink remoteMessageSink, IProgressMonitor progressMonitor, String taskName, FileInfo file) in c:\Server\Projects\MbUnit v3\Work\src\Gallio\Gallio\Model\DotNetTestDriver.cs:line 195
   at Gallio.Model.DotNetTestDriver.ExploreOrRun(ITestIsolationContext testIsolationContext, TestPackage testPackage, TestExplorationOptions testExplorationOptions, TestExecutionOptions testExecutionOptions, IMessageSink messageSink, IProgressMonitor progressMonitor, String taskName) in c:\Server\Projects\MbUnit v3\Work\src\Gallio\Gallio\Model\DotNetTestDriver.cs:line 156
   at Gallio.Model.DotNetTestDriver.ExploreImpl(ITestIsolationContext testIsolationContext, TestPackage testPackage, TestExplorationOptions testExplorationOptions, IMessageSink messageSink, IProgressMonitor progressMonitor) in c:\Server\Projects\MbUnit v3\Work\src\Gallio\Gallio\Model\DotNetTestDriver.cs:line 141
   at Gallio.Model.DefaultTestFrameworkManager.FilteredTestDriver.<>c__DisplayClass1b.<ExploreImpl>b__19(ITestDriver driver, IList`1 items, Int32 driverCount) in c:\Server\Projects\MbUnit v3\Work\src\Gallio\Gallio\Model\DefaultTestFrameworkManager.cs:line 446
   at Gallio.Model.DefaultTestFrameworkManager.FilteredTestDriver.ForEachDriver[T](MultiMap`2 testFrameworkPartitions, Func`4 func) in c:\Server\Projects\MbUnit v3\Work\src\Gallio\Gallio\Model\DefaultTestFrameworkManager.cs:line 528
   --- End of inner exception stack trace ---
HResult: -2146233088
   at Gallio.Model.DefaultTestFrameworkManager.FilteredTestDriver.ForEachDriver[T](MultiMap`2 testFrameworkPartitions, Func`4 func) in c:\Server\Projects\MbUnit v3\Work\src\Gallio\Gallio\Model\DefaultTestFrameworkManager.cs:line 534
   at Gallio.Model.DefaultTestFrameworkManager.FilteredTestDriver.ExploreImpl(ITestIsolationContext testIsolationContext, TestPackage testPackage, TestExplorationOptions testExplorationOptions, IMessageSink messageSink, IProgressMonitor progressMonitor) in c:\Server\Projects\MbUnit v3\Work\src\Gallio\Gallio\Model\DefaultTestFrameworkManager.cs:line 439
   at Gallio.Runner.DefaultTestRunner.Explore(TestPackage testPackage, TestExplorationOptions testExplorationOptions, IProgressMonitor progressMonitor) in c:\Server\Projects\MbUnit v3\Work\src\Gallio\Gallio\Runner\DefaultTestRunner.cs:line 242

**Comment by DrPhilG** [comment]
Hi Bobby, thanks for bringing this to our attention. We tested the code last week before we published the new tutorial, I’ve asked our resident C# expert to take another look. We will have a corrected version up as soon as we can diagnose the problem. 

Phil 

Phil Gochenour, PhD
Senior Technical Writer 
philg@saucelabs.com <mailto:philg@saucelabs.com>
Sauce Labs <http://saucelabs.com/> | Sauce blog <http://sauceio.com/>

**Comment by DrPhilG** [comment]
Hi Bobby, 

we’ve tried running the sample code again on our side and everything works as expected. Can you provide us with any more information about what happened on your end so we can try to reproduce the problem?

Thanks, 

Phil 
Phil Gochenour, PhD
Senior Technical Writer 
philg@saucelabs.com <mailto:philg@saucelabs.com>
Sauce Labs <http://saucelabs.com/> | Sauce blog <http://sauceio.com/>
